### ISSUE TITLE
Simulator

### ISSUE THREAD

**Issue by itjunkii83** [randikachan/DeviceType#2]
Hello,

Thanks for making this available. I found when running on the simulator it returns true for both iphone 6 and iphone 6 Plus when I am running a iphone 6 Plus - is this the intended behavior?

**Comment by itjunkii83** [comment]
I see your device flag...I guess I am worried this will truly work in the wild. I have over 100K users and if this fails it will be a disaster...assuming you have tested with all physical devices?

**Comment by itjunkii83** [comment]
Any specific reason why you didn't just measure screen size?

**Comment by randikachan** [comment]
@itjunkii83 You are very welcome to use this within your project. Currently I had used this within one of the freelance applications I have implemented. While developing that, I had to check this on following list of devices.

- iPhone 5S
- iPhone 6S
- iPhone 6S+
- iPad 2

In all of those this code did work accurately.

And yes, when you are running this code on iOS Simulators, you have to specify the Device flag which is suitable for the iOS Simulator you are running the code on.

How can I be helpful to you further more? :-)

**Comment by randikachan** [comment]
@itjunkii83 Didn't hear from you after your last interaction. What's your decision about this utility classes?

**Comment by itjunkii83** [comment]
Hello,

 Apologize for not responding, it appears these were going into my spam box. I decided to go with some size bass solutions mainly because of the difference between zoomed and non-zoomed devices introduced from iPhone 6 on that make programming for layout  quite tricky. I'd be happy to share the code with you if you were interested? this was the primary for my decision not to use your library, since what I was doing was visual I really had to rely on the simulator to give me all different types of devices in different states.

**Comment by randikachan** [comment]
Yes It's interesting to see your solution. So I can think of other ways to achieve the same functionality.

I built this simple classes for same alike reason, where I had to check the which device the app runs on and then change the Autolayout constraints in order to make the UI properly appear.

`
if ([DeviceTypes isIPhone5SizedDevice]) {  // iPhone5 Size screens - 1136 x 640 pixels 326ppi`

    // Do your required logic relevant to iPhoneSE Size screens or devices (iPhone5, 5S, SE)

`} else if ([DeviceTypes isIPhone6SizedDevice]) { // iPhone7 Size screens - 750 x 1334 pixels ~ 326ppi`

    // Do your required logic relevant to iPhone7 Size screens or devices (iPhone6, 6S, 7)

`} else if ([DeviceTypes isIPhone6PlusSizedDevice]) { // iPhone7+ Size screens ~ 1080 x 1920 pixels ~ 401ppi`

`    // Do your required logic relevant to iPhone7+ Size screens or devices (iPhone6+, 6S+, 7+)`

`} else if ([DeviceTypes isIPad]) {`

`    // Do your required logic relevant to iPads`

}`

Like wise you still can achieve what you need by using these classes. And don't forget following set of methods! :-)

`+ (NSString*)deviceModelName
    Retrieves back the device name or if not the machine name.
+ (NSString *)getDeviceType
    Simply does the same thing which [[UIDevice currentDevice] model] does.
+ (CGFloat)getDeviceWidth
+ (CGFloat)getDeviceHeight`

**Comment by itjunkii83** [comment]
Thanks @randikachan appreciate your explanation and I will definitely give that a try 👍

**Comment by randikachan** [comment]
Hope @itjunkii83 might have got the answer he expected, hence closing the issue by here! 👍 :-)
